before_script:
  - uname -a 
  - cat /etc/lsb-release
  - sudo apt-get install haskell-platform
  - cabal update
  - cabal install cabal-install
  - cabal install json-0.4.4
  - cabal install pandoc

rvm:
  - 1.9.3
script: pandoc -v
